### ISSUE TITLE
Have to change the playback speed for every single video I am playing...

### ISSUE THREAD

**Issue by ymolliks** [Good-Will-Coding/Plex-Pace#1]
It works great when I change the speed but the real pain is I have to change the speed for every single video. I want the speed to stay at 1.5x for every single plex video not for just one video...Please add the ability to remember playback speed.

**Comment by BreakBB** [comment]
Hey @yeasinmollik @Kethet @Narex45635 and @ejazrasool 

I was able to contact the author of this project @Good-Will-Coding and also provided a PR to tackle this issue. Hoping this will make it into a new version of Plex Pace.
